name: Image node Stage1

on:
  push:
    paths:
      - 'containers/nym-base/nym-node-latest.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: container login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Compiling new node software
      run: |
        docker build . --file containers/nym-node/stage1 --compress --tag chaincrucial/nym-node:stage1
    - name: docker push node stage 1
      run: |
        docker push chaincrucial/nym-node:stage1
    - name: docker dispatch node stage 2
      run: |
        curl -XPOST \
        -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -H 'Content-Type: application/json' \
        https://api.github.com/repos/TrevorBenson/silver-tribble/actions/workflows/image-node-stage2.yml/dispatches \
        --data '{"ref": "main"}'
